"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import ThemeProvider from "@/providers/PokemonsProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const [dataFromChild, setDataFromChild] = useState([]);

  // function handleDataFromChild(data) {
  //   setDataFromChild(data);
  // }

  return (
    <html lang="en">
      <body className="bg-red-500">
        <div className="flex flex-col">
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
